## eigendecomposition exercise

In [1]:
# import numpy
import numpy as np

**Task:** Create a matrix (2x2) called matrix 'A'.


In [22]:
M = np.arange(1,10).reshape(3,3)

In [23]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
A = np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

**Task:** Define the function `'shape_2x2'` which checks if a matrix has a (2x2) shape.

In [25]:
"""
Define the function 'shape_2x2' which checks if a matrix has a (2x2) shape.

PARAMS:
    matrix (numpy.ndarray) - matrix to check
RETURN:
    True (bool) - if matrix has shape 2x2
    False (bool) - if matrix has not shape 2x2

"""


"\nDefine the function 'shape_2x2' which checks if a matrix has a (2x2) shape.\n\nPARAMS:\n    matrix (numpy.ndarray) - matrix to check\nRETURN:\n    True (bool) - if matrix has shape 2x2\n    False (bool) - if matrix has not shape 2x2\n\n"

In [26]:
def shape_2x2(matrix):
    rows = len(matrix)
    columns = len(matrix[0])
    if rows == columns:
        if rows == 2:
            return True
        else:
            return False
    else:
        return False

In [62]:
shape_2x2(A)

True

**Task:** Define the function `'determinant_2x2'` which computes the determinant of a (2x2) matrix.

Do not forget to check the shape of  the input matrix.

In [ ]:
"""
Define the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.

PARAMS:
    matrix (numpy.ndarray) - matrix to compute determinant
RETURN:
    det (float) - matrix determinant

"""


In [63]:
def determinant_2x2(matrix):
    if shape_2x2(matrix) == True:
        return np.linalg.det(matrix)
    else:
        pass

**Task:** Call the function `'determinant_2x2'` on matrix 'A'.

In [34]:
determinant_2x2(A)

-2.0000000000000004

**Task:** Compute the eigenvalues of matrix 'A' with numpy.

In [35]:
from numpy import linalg as LA

In [150]:
LA.eigvals(A)

array([-0.37228132,  5.37228132])

**Task:** Print the eigenvalues.

In [151]:
LA.eigvalsh(A)

array([-0.85410197,  5.85410197])

In [152]:
LA.eigh(A)

(array([-0.85410197,  5.85410197]),
 array([[-0.85065081,  0.52573111],
        [ 0.52573111,  0.85065081]]))

**Task:** Print  the eigenvectors.

In [39]:
LA.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

**Task:** Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.

Do not use the np.linalg.eig function. Use your 'shape_2x2' and your 'determinant_2x2' functions. Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of a 2x2 matrix?:

- https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/

In [ ]:
"""
Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

"""

In [99]:
import cmath

In [147]:
def eig_2x2(matrix):
    if shape_2x2(matrix) == True:
        tr = matrix[0][0] + matrix[1][1]
        p1 = (tr + cmath.sqrt(tr**2 - 4*determinant_2x2(matrix)))/2
        p2 = (tr - cmath.sqrt(tr**2 - 4*determinant_2x2(matrix)))/2
        return p1,p2, matrix.dot(p1), p2*matrix
    else:
        return "matrix isnt 2x2"

In [1]:
def eig_2x2(matrix):
    if not shape_2x2(matrix):
        return None
    # sum of matrix diagonal
    matrix_trace = matrix.trace()
    # 0j because np.sqrt:  np.sqrt(-1) => nan, np.sqrt(-1 + 0j) => 1j
    inside_sqrt = matrix_trace**2 - 4*determinant_2x2(matrix) + 0j
    eigenvalues = [((matrix_trace - np.sqrt(inside_sqrt))/2),
                   ((matrix_trace + np.sqrt(inside_sqrt))/2)]
    # only real part of number if imaginary part is equal to zero
    eigenvalues = np.sort(np.array([v.real if v.imag == 0 else v for v in eigenvalues]))
    eigenvectors = []
    for eigv in eigenvalues:
        matrix_minus_eig = matrix - eigv*np.eye(matrix.shape[0])
        # matrix[0,0]*x + matrix[0,1]*y = 0 
        # possible solution => x= -matrix[0,1], y= matrix[0,0]
        # possible solution => x= matrix[0,1], y= -matrix[0,0]
        eigenvector = np.array([-matrix_minus_eig[0,1], matrix_minus_eig[0,0]])
        # vector with lenght of 1 
        eigenvector_norm = eigenvector/np.linalg.norm(eigenvector)
        eigenvectors.append(eigenvector_norm)
    # vectors as columns
    eigenvectors = np.array(eigenvectors).T
    return eigenvalues, eigenvectors

**Task:** Call the function `'eig_2x2'` on matrix 'A'.

In [149]:
eig_2x2(A)

((5.372281323269014+0j),
 (-0.3722813232690143+0j),
 array([[ 5.37228132+0.j, 10.74456265+0.j],
        [16.11684397+0.j, 21.48912529+0.j]]),
 array([[-0.37228132+0.j, -0.74456265+0.j],
        [-1.11684397+0.j, -1.48912529+0.j]]))

**Task:** Compare your results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [118]:
np.allclose([5.372281323269014+0j, -0.3722813232690143+0j], 
            [-0.85410197,  5.85410197])

False

**Task:** Define matrix B = np.array([[0,1],[-1,0]]) 

In [102]:
B = np.array([[0,1],[-1,0]]).reshape(2,2)
B

array([[ 0,  1],
       [-1,  0]])

**Task:** Compute the eigenvalues and the eigevectors of matrix 'B' with numpy and with your `'eig_2x2'` function.

In [108]:
eig_2x2(B)

(1j,
 -1j,
 array([[ 0.+0.j,  0.+1.j],
        [-0.-1.j,  0.+0.j]]),
 array([[0.+0.j, 0.-1.j],
        [0.+1.j, 0.+0.j]]))

**Task:** Compare the results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [139]:
np.allclose(LA.eigvals(B),
            [1j, -1j])

True

In [140]:
LA.eigvals(B)

array([0.+1.j, 0.-1.j])

In [146]:
LA.eig(B)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        +0.70710678j, 0.        -0.70710678j]]))

**Task:** Print the eigenvalues and the eigenvectors. Why are the solutions different?